version: '3'

services:
  db:
    image: mysql/mysql-server:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: golang_research
      MYSQL_USER: arun
      MYSQL_PASSWORD: password
    expose:
      - 3306
    ports:
      - "3306:3306"

  redis:
    image: "redis:alpine"
    container_name: redis
    ports:
      - "6379 :6379"
    networks:
      - proxynet

networks:
  proxynet:
    external:
      name: custom_network