version: '3'

services:
  db:
    image: mysql/mysql-server:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: golang_research
      MYSQL_USER: arun
      MYSQL_PASSWORD: password
    networks:
      - proxynet
    ports:
      - "3306:3306"

  redis:
    image: "redis:alpine"
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - proxynet

  webapi:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    container_name: "web_user_tools"
    ports:
      - "3000:3000"
    networks:
      - proxynet
    command: ["./docker/wait-for-it.sh", "db:3306", "--", "./main/web_service"]
    environment:
      API_PORT: 3000
      DATABASE_URL: arun:password@tcp(172.17.0.1:3306)/golang_research?charset=utf8&parseTime=True&loc=Local
      DATABASE_DIALECT: mysql
      REDIS_ADDRESS: 172.17.0.1:6379
      REDIS_PASSWORD: ""

networks:
  proxynet:
    external:
      name: custom_network