version: '3'

services:
  webapi:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    container_name: "web_user_tools"
    ports:
      - "3000:3000"
    networks:
      - proxynet
    environment:
      API_PORT: 3000
      DATABASE_URL: arun:password@tcp(172.17.0.1:3306)/golang_research?charset=utf8&parseTime=True&loc=Local
      DATABASE_DIALECT: mysql
      REDIS_ADDRESS: 172.17.0.1:6379
      REDIS_PASSWORD: ""

networks:
  proxynet:
    external:
      name: custom_network